### ISSUE TITLE
not found news_doc.csv

### ISSUE THREAD

**Issue by Jyonn** [yflyl613/NewsRecommendation#1]
hi, thanks for your code, but i met the error "No such file or directory: './dataset/news_docs.tsv'", could you pls tell me how to generate news_doc.tsv?

**Comment by yflyl613** [comment]
You can use the script provided with the MIND dataset to crawl news features. The link is in [https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md](url)

**Comment by yflyl613** [comment]
> hi, thanks for your code, but i met the error "No such file or directory: './dataset/news_docs.tsv'", could you pls tell me how to generate news_doc.tsv?

You can use the script provided with the MIND dataset to crawl news features. The link is in [https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md](url)

**Comment by TJ2364** [comment]
> > hi, thanks for your code, but i met the error "No such file or directory: './dataset/news_docs.tsv'", could you pls tell me how to generate news_doc.tsv?
> 
> You can use the script provided with the MIND dataset to crawl news features. The link is in [https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md](url)

I tried to crawl the data, but failed. This is too difficult for me. Is it convenient for you to publish this news_doc.tsv？

**Comment by yflyl613** [comment]
> > > hi, thanks for your code, but i met the error "No such file or directory: './dataset/news_docs.tsv'", could you pls tell me how to generate news_doc.tsv?
> > 
> > 
> > You can use the script provided with the MIND dataset to crawl news features. The link is in [https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md](url)
> 
> I tried to crawl the data, but failed. This is too difficult for me. Is it convenient for you to publish this news_doc.tsv？

I'm afraid I can't. As it is mentioned in the introduction of the [MIND Dataset](https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md), the full content body of MSN news articles are not made available for download due to licensing structure. I got access to those news body during my intern in MSRA. You may choose not to use the news body and only use those available news information instead, such as title, abstract, category and subcategory.

**Comment by TJ2364** [comment]
> > > > hi, thanks for your code, but i met the error "No such file or directory: './dataset/news_docs.tsv'", could you pls tell me how to generate news_doc.tsv?
> > > 
> > > 
> > > You can use the script provided with the MIND dataset to crawl news features. The link is in [https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md](url)
> > 
> > 
> > I tried to crawl the data, but failed. This is too difficult for me. Is it convenient for you to publish this news_doc.tsv？
> 
> I'm afraid I can't. As it is mentioned in the introduction of the [MIND Dataset](https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md), the full content body of MSN news articles are not made available for download due to licensing structure. I got access to those news body during my intern in MSRA. You may choose not to use the news body and only use those available news information instead, such as title, abstract, category and subcategory.

Thank you very much for your reply and please excuse me for taking the liberty. I will take your advice, and at the same time，I will try to crawl the news_docs.tsv again.
