### ISSUE TITLE
model and data use gpu

### ISSUE THREAD

**Issue by chen849157649** [yflyl613/NewsRecommendation#2]
thank you with share codes, cannot use gpu train, why?

**Comment by yflyl613** [comment]
> thank you with share codes, cannot use gpu train, why?

Could you share how you run training? I can train with GPU before. The code should be okay.

**Comment by chen849157649** [comment]
@yflyl613 ,  python main.py --cpu False --pre True --n_GPUs 4，print input data on cpu
![微信图片_20210514102042](https://user-images.githubusercontent.com/32058220/118211081-2267ea00-b49e-11eb-96d2-948c4f5c9e0d.png)， the data on cpu?  train speed is very slow

**Comment by yflyl613** [comment]
> @yflyl613 , python main.py --cpu False --pre True --n_GPUs 4，print input data on cpu
> ![微信图片_20210514102042](https://user-images.githubusercontent.com/32058220/118211081-2267ea00-b49e-11eb-96d2-948c4f5c9e0d.png)， the data on cpu? train speed is very slow
It seems that I forgot to put the batch onto GPU. I will fix this later.
