### ISSUE TITLE
train speed

### ISSUE THREAD

**Issue by chen849157649** [yflyl613/NewsRecommendation#4]
hello, NAML , The speed of model training is very slow  on GPU. Is this normal? How fast did you train ?

**Comment by yflyl613** [comment]
> hello, NAML , The speed of model training is very slow on GPU. Is this normal? How fast did you train ?

I can't remember my training speed, but it shouldn't be very slow. It should only take several minutes if you use MIND-small for training with 4 GPUs. Maybe you need to check whether both the data and the model are on the GPU.
