### ISSUE TITLE
what is the comfiguration for NRMS model?

### ISSUE THREAD

**Issue by YahongANN** [yflyl613/NewsRecommendation#7]
Hi, I want to know how to conduct NRMS model in command line?
#model = module.Model(args, embedding_matrix, len(category_dict), len(subcategory_dict))     #modify for NAML
model = module.Model(args, embedding_matrix)      #modify for NRMS
when I start to training NRMS it gives error information like this "RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`"

**Comment by yflyl613** [comment]
> Hi, I want to know how to conduct NRMS model in command line? #model = module.Model(args, embedding_matrix, len(category_dict), len(subcategory_dict)) #modify for NAML model = module.Model(args, embedding_matrix) #modify for NRMS when I start to training NRMS it gives error information like this "RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`"

Using `model = module.Model(args, embedding_matrix)` should be right. You may first run the code with CPU to see more detailed error information. The current error information with GPU does not provide much useful information.
